# Generated by Django 2.2.17 on 2021-03-31 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import upskill_photography.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('picture_id', models.UUIDField(default=upskill_photography.models.uuid4_hex, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=upskill_photography.models.rename_image)),
                ('thumbnail', models.ImageField(blank=True, default=None, editable=False, null=True, upload_to=upskill_photography.models.rename_thumbnail)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=8, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upskill_photography.Category')),
                ('uploading_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upskill_photography.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upskill_photography.Picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upskill_photography.UserProfile')),
            ],
        ),
    ]
