# Generated by Django 2.2.17 on 2021-03-19 10:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upskill_photography', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picture',
            new_name='profile_picture',
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('picture_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='user_uploads/<django.db.models.fields.related.ForeignKey>')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/<django.db.models.fields.related.ForeignKey>')),
                ('category', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('uploading_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upskill_photography.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upskill_photography.Picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upskill_photography.UserProfile')),
            ],
        ),
    ]
