# Generated by Django 2.2.17 on 2021-03-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upskill_photography', '0002_auto_20210319_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='user_uploads/'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
